### ISSUE TITLE
Better documentation for "buchhaltung update"

### ISSUE THREAD

**Issue by varac** [johannesgerer/buchhaltung#11]
I'm trying buchhaltung for the first time. Setting it up, I failed after `buchhaltung update` because the `ledgers.imported` file is not present, and I have no idea how to add it properly:

```
The hledger journal file "/home/varac/hledger/buchhaltung-import.ledger" was not found.
Please create it first, eg with "hledger add" or a text editor.
Or, specify an existing journal file with -f or LEDGER_FILE.
```

Is this file mandatory ? When I don't want to import already existing .csv files but start fresh with buchhaltung ?

**Comment by varac** [comment]
A simple `touch /home/varac/hledger/buchhaltung-import.ledger` was sufficcient. I propose that this should be done automatically when the file is not present.

**Comment by johannesgerer** [comment]
Yes, Touch is enough, I should add it to the docs.

Not doing it automatically is a safety feature.  It prevents you from importing into the wrong for without realising it.
