### ISSUE TITLE
A better way to handle Starbucks

### ISSUE THREAD

**Issue by ohbadiah** [johannesgerer/buchhaltung#13]
I'm referring to the Starbucks example from the documentation. I'm still new to this, but I find it difficult to manually add corresponding and offsetting transactions to the more general categories I choose for the sake of consistency during `match`. What if it were possible to add offsetting transactions during the match process itself? Or perhaps a posting or transaction could be marked to be ignored by the classifier.

**Comment by johannesgerer** [comment]
Do you think the configuration options starting with `ignoredAccounts` can help you?
(See the config.yml file)
