### ISSUE TITLE
Better documentation for the match process

### ISSUE THREAD

**Issue by varac** [johannesgerer/buchhaltung#15]
I still haven't figuered out what the '>' or '<' symbols mean in the match process prompt:

    `[<, >, save, RET]:`

Please update the documentation so all options are described.
Futher more, how do I skip one transaction that I don't want to match right now and carry on matching ?

**Comment by johannesgerer** [comment]
Yes, documentation is needed here. Please feel to issue a pull request.

Hitting `>` should allow you to skip. Is this working?

**Comment by varac** [comment]
Aha! It doesn't work at _hitting_ `>` but `entering` `>` moves forward and `<` moves backwards, nice.

**Comment by johannesgerer** [comment]
Fixed in 65ab169
