### ISSUE TITLE
Allow absolute path in config.yml

### ISSUE THREAD

**Issue by jottr** [johannesgerer/buchhaltung#18]
I've tried to properly set up the path to my journal files in the relevant `config.yml` but found it difficult to do so.   
Neither the documentation nor the config example make it obvious whether the `mainLedger` and `imported` keys expect absolute or relative paths.  
I.e. I would like to point them to `~/jottr/.ledger/`, but when using the k/v pair of `mainLedger: ~/.ledger/`, `buchhaltung setup` creates a subdirectory in `~/.buchhaltung/~/jottr/.ledger` instead.  

Is there a means to config `buchhaltung` with absolute paths?

**Comment by johannesgerer** [comment]
Absolute paths are supported, but unfortunately path aliases like the  '~' are not supported currently. Use '/home/whatever' instead and it should work.

**Comment by johannesgerer** [comment]
Please reopen if the above does not fix your problem.
