### ISSUE TITLE
provide example config

### ISSUE THREAD

**Issue by robertschulze** [johannesgerer/buchhaltung#2]
from the README:

cp config-sample ~/.buchhaltung/config

however, the config-sample file is missing, unfortunately.

**Comment by johannesgerer** [comment]
Yes you are right! The current commit is not yet fully working. I will fix this in the next few days. Sorry, and thank you for you patience!

**Comment by mxgr7** [comment]
+1

**Comment by johannesgerer** [comment]
Please read the updated [readme](https://github.com/johannesgerer/buchhaltung/blob/master/README.md) and use the new [config file](https://github.com/johannesgerer/buchhaltung/blob/master/config.yml).
