### ISSUE TITLE
Documentation: Explain relationship between different ledger files

### ISSUE THREAD

**Issue by jottr** [johannesgerer/buchhaltung#20]
I've tried setting up buchhaltung with the `mainLedger` and `imported` keys set to distinctive ledger files.  
After reading the documentation and the comments in [`config.yml`](https://github.com/johannesgerer/buchhaltung/blob/master/config.yml#L7), I still can't quite grasp the relationship between the two files.   
I first understood it like so: `imported` stores all the transactions recently imported via the `update` command.  
After they were matched via the  `match` command, the newly matched transaction are written to the `mainLedger`-file. 

This seems to not be the case, since only the `imported`-ledger is edited in place, i.e. the information is only stored in the `imported` ledger, and not transferred into `mainLedger`.

**Comment by johannesgerer** [comment]
Yes, `imported` contains imported transactions (via `update` or `import` commands). At first they will be posted  I to a `TODO` account which will then be changed to the account you entered through `match`.

Transactions stay in `imported` and form the basis of Bayesian learning based suggestions for `match`.

**Comment by johannesgerer** [comment]
Please reopen if any questions.
