### ISSUE TITLE
Using buchhaltung and gnucash at the same time

### ISSUE THREAD

**Issue by fishman** [johannesgerer/buchhaltung#25]
I've been using gnucash and i recently started trying to use aqbanking. It seems to me that they will both use the same accounts in aqbanking which in turns means whenever I use one it will override the state of the other. So buchhaltung on it's first use will add the transactions since the last gnucash fetch. Maybe I'm wrong and something else happens, but at the very least aqbanking seems to remember when the last transaction was fetched.

Is there any way i can make buchhaltung fetch all transactions?

**Comment by johannesgerer** [comment]
You are raising an important point. 

Let me first explain how buchhaltung uses Aqbanking:

Buchhaltung will always ask AqBanking for every transaction it has and then use its own logic to understand which of these transactions have already been imported. This mechanism also allows you to find duplicate transactions in cases where the bank changed its format (see [here](https://github.com/johannesgerer/buchhaltung#resolve-duplicates)). 

Now to answer your question:

If you set the[`aqBanking.configDir`](https://github.com/johannesgerer/buchhaltung/blob/master/config.yml) config setting to a directory different from the one used by GnuCash there will be _no_ interaction between buchhaltung and GnuCash.
