### ISSUE TITLE
buchhaltung on stackage

### ISSUE THREAD

**Issue by dotlambda** [johannesgerer/buchhaltung#9]
Please add your package to Stackage as described [here](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md).

**Comment by varac** [comment]
Yes please!

**Comment by RichiH** [comment]
Any progress on this? I would love to see buchhaltung packaged for Debian, but being on stackage is more or less a requirement.

**Comment by RichiH** [comment]
PS: Downgrading hledger to an old version will not work in Debian. Is there a chance to upgrade your deps?

**Comment by johannesgerer** [comment]
Yes, absolutely. I might find time this weekend.

**Comment by RichiH** [comment]
That would be greatly appreciated.

Once it's in stackage and the dependencies are updated, I will make
sure it makes it way into Debian.

**Comment by johannesgerer** [comment]
https://github.com/fpco/stackage/pull/3267
